server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service

logging:
  level:
    org.springframework.security: TRACE
      
security:
  user:
    name: root
    password: password
  oauth2:
    resource:
#      loadBalanced: true
      userInfoUri: http://localhost:9998/user
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/