server:  
  port: ${PORT:8765}

spring:  
  application:
    name: gateway-server
  datasource:
    url: jdbc:mysql://192.168.99.100:33306/oath2?useSSL=false
    username: default
    password: default

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
      
zuul:
  routes:  
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
    account:
      path: /account/**
      sensitiveHeaders: 
      serviceId: account-service
    customer:
      path: /customer/**
      sensitiveHeaders: 
      serviceId: customer-service
            
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  user:
    name: root
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:8765/uua/oauth/token
      userAuthorizationUri: http://localhost:8765/uua/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:8765/uaa/user
      preferTokenInfo: false  
  sessions: ALWAYS 

proxy:
  auth:
    routes:
      customer: oauth2
      account: oauth2
          
#security:
#  oauth2:
#    sso:
#      loginPath: /uaa/login      
#    client:
#      accessTokenUri: http://localhost:8765/uua/oauth/token
#      userAuthorizationUri: http://localhost:8765/uua/oauth/authorize
#      clientId: acme
#      clientSecret: secret
#      clientAuthenticationScheme: form   
#    resource:
#      userInfoUri: http://localhost:9999/user
#      preferTokenInfo: false  
#  sessions: ALWAYS 