server:  
  port: ${PORT:9999}

spring:  
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://192.168.99.100:33306/oauth2?useSSL=false
    username: default
    password: default
    
logging:
  level:
    org.springframework.security: TRACE
      
security:
#  basic:
#    enabled: false
  user:
    name: root
    password: password
  oauth2:
    client:
      client-id: acme
      client-secret: secret
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/